[Circuit_Version]
Circuit_Type = "idcNullifier"

[Circuit_Build]
Circom_Version = "circom compiler 2.1.5"
GitHub_URL = "https://github.com/Discreetly/IdentityCommitmentNullifierCircuit.git"
Git_Commit = "3cd6a18"
Compilation_Time = 1690859896

[Files]
Wasm = "circuit.wasm"
Wasm_SHA256SUM = "a49e8077f55f964e64adc36eec06411785ba84c4efd1f44642b66831df3dc20a"
Zkey = "final.zkey"
Zkey_SHA256SUM = "9330067dcdc0e72e1502dbb4f0d1dc157fc6e1bddda725eabf2b5d176a8e183d"
Verification_Key = "verification_key.json"
Verification_Key_SHA256SUM = "8680697991703b83ddce3ba1365c26ad0ad0f829727e02f678612ae70cbf75cc"
