[Circuit_Version]
Circuit_Type = "idcNullifier"

[Circuit_Build]
Circom_Version = "circom compiler 2.1.5"
GitHub_URL = "https://github.com/Discreetly/IdentityCommitmentNullifierCircuit.git"
Git_Commit = "b940865"
Compilation_Time = 1698193072

[Files]
Wasm = "circuit.wasm"
Wasm_SHA256SUM = "410da93349f51f96dfb1bbb2d6578617a3de2494cf46d1ca6c1910a0098c82b8"
Zkey = "final.zkey"
Zkey_SHA256SUM = "f6a8af84b662111a05029facc2dab6e74fcb9e79e63ce0132fd245a0eb460c3f"
Verification_Key = "verification_key.json"
Verification_Key_SHA256SUM = "0823bf5476835f00dc665c3b579520b84f44ded39b6cc6a2d73d6439e5192564"
